### ISSUE TITLE
Are these actually supported?

### ISSUE THREAD

**Issue by saghul** [matrix-org/vodozemac-bindings#9]
We currently use libolm in Jitsi Meet and since it got deprecated I was considering upgrading to vodozemac but:

- There is no published package that I can find
- These bindings are pinned to a vodozemac version which is over 2 years old
- There is zero tests or documentation
- No updates for 2 yuears in this repo

What is the path forward here, for those of us using libolm in JS, from a browser?

**Comment by IgorKhomenko** [comment]
In a case it helps, this is how the lib can be connected to Web project:

- Go to [matrix-org/vodozemac-bindings](https://github.com/matrix-org/vodozemac-bindings) and run the following command `wasm-pack build --target web --dev`
- Move the generated files from the `pkg` folder to the `vendors/vodozemac` folder in YOUR project
- Declare the folder in package.json as a built-in library: `"vodozemac-javascript": "file:vendors/vodozemac"`
- Import everything from the library, call it to initialize it in the project, and now you can use it anywhere in the project
```
import initVodozemac, { Account } from "vodozemac-javascript";

initVodozemac().then((res) => {
   const a = new Account();
});
```

**Comment by poljar** [comment]
For what its worth, we're going to discuss this tomorrow in a meeting.

**Comment by saghul** [comment]
> In a case it helps, this is how the lib can be connected to Web project:
> 
> 
> 
> - Go to [matrix-org/vodozemac-bindings](https://github.com/matrix-org/vodozemac-bindings) and run the following command `wasm-pack build --target web --dev`
> 
> - Move the generated files from the `pkg` folder to the `vendors/vodozemac` folder in YOUR project
> 
> - Declare the folder in package.json as a built-in library: `"vodozemac-javascript": "file:vendors/vodozemac"`
> 
> - Import everything from the library, call it to initialize it in the project, and now you can use it anywhere in the project
> 
> ```
> 
> import initVodozemac, { Account } from "vodozemac-javascript";
> 
> 
> 
> initVodozemac().then((res) => {
> 
>    const a = new Account();
> 
> });
> 
> ```

I know how to do that, but I shouldn't need to. In addition that doesn't solve the fact that the bindings are 2 years behind the library they bind.

**Comment by saghul** [comment]
> For what its worth, we're going to discuss this tomorrow in a meeting.

Thank you!

**Comment by poljar** [comment]
Sadly the answer is, no, these are not supported.

I kinda expected this situation and pulled the Python bindings, which I'm personally invested in, into a separate repo: https://github.com/matrix-nio/vodozemac-python.

Some other folks seem to have pulled the c++ bindings out as well: https://github.com/matrix-nio/vodozemac-python.

It would probably make most sense to do the same with the WASM bindings.

Sorry.

**Comment by poljar** [comment]
Opened https://github.com/matrix-org/vodozemac-bindings/pull/10 to make this more prominent and official.

**Comment by saghul** [comment]
I appreciate the honesty.
